### ISSUE TITLE
Team3-conduct-decision-thoughts

### ISSUE THREAD

**Issue by liux2** [Allegheny-Computer-Science-203-S2020/cs203-S2020-conduct#3]
For the decision-making process, sometimes, technical teams will have the issue that a decision could take an unnecessarily long time to make. That would be inefficient. 

  * Question 1: how can technical teams accelerate the process, and when should the team terminate the process?
  * Question 2: There are urgent and non-urgent issues, team members should always decide the priority of the issue first.
  * Question 3: When the team members have disagreements, how do they solve the disagreement? How do members prevent one member from dominating the team?
  * Question 4: How do we avoid bias toward any idea, tool, algorithm, program, or any other objects during decision making?

The commit can be found at https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-conduct/commit/93852e82abc66e06c89560a9f7ec731f65e715fe

**Comment by Jordan-A** [comment]
Great questions! 

For the first question I think it would be helpful if groups determined how long a particular decision would take to implement.  If it is unreasonably goes over the amount of time it was predicted to take, then it can be terminated and a new approach can be pursued.

For question 2 I think that the urgent issues should always be the priority first, and I'll update the decisions to reflect this value.

**Comment by Jordan-A** [comment]
### Suggested Fix 
Teams should determine how long a decision will
take to implement. If it is unreasonably over the amount of time it was predicted
to take with no end in sight, it should be terminated and a new approach should be
pursued.

* Team members should decide the priority of the issue before passing a decision.

**Comment by santacruzm** [comment]
I agree with Jordan's fix and will hint that in my suggested fix below. The issue should be terminated if it involves an unreasonable amount of time to resolve. In addition, an issue should be terminated if it was consulted with technical leaders, point-person, or the professor and no resolution was found. 

**Suggested Fix** 
In regards to the issue presented above, the project manager along with the rest of the team should evaluate and organize a strategic plan for an issue and timing. In particular, tasks to solve the issue should be delegated among all team members to increase efficiency.  

- Delegate tasks to all group members

**Comment by Jordan-A** [comment]
I agree with the point in @santacruzm suggested fix. I will add it to the conduct file.

For the questions from @liux2, I think the third question is already answered by part of the decisions paragraph "When a choice is being disputed in a group a poll can be used to make the decision with a 3/4th majority."

In the fourth question I think the best way we can avoid bias is by making sure 3/4th of a group needs to have consensus in order for an agreement to be made, and by delegating all tasks to all members of a group.

Thanks for the feedback!

**Comment by liux2** [comment]
I agree with Marisol, in each project cycle period, team members should make schedules based on reality.

**Comment by hodevin** [comment]
**Suggested Fix**
**2.** I suggest that if there are urgent issues, they should obviously be addressed first. Maybe we can label certain issues with an urgent tag or something that will take priority over all other issues. This way, we can maintain the integrity of the issue tracker.
- Add a "URGENT" tag to each prioritized issue.

**Comment by lussierc** [comment]
With regards to Question 4 and avoiding biases, something that could also be added would be information that talks about the standard for team members in the class being that they should approach situations without bias. With this, if there is still bias, I like the idea of using the 3/4th majority or a similar majority vote when needed, like @Jordan-A mentioned, as this information is already included in our Decisions section.

**Comment by lussierc** [comment]
With regard to Question 2, I feel that team members should prioritize tasks based on their own intuition in order to complete the most important things first. With this, I feel that team leaders should try to create schedules that will outline these priorities' importance. However, for the most part, team members should make the overall/final call on how they prioritize their tasks because it is hard to say what issues may come up during the software development process that might need to be prioritized more than others.

**Comment by Jordan-A** [comment]
I agree with your thoughts of adding an "urgent" tag. 👍 

@lussierc  Thanks! I thought having a 3/4th majority should reduce group discord surrounding potentially unpopular decisions. 👍 

### Suggested Fix:
* Team members should decide the priority of the issue using a "URGENT" tag.

**Comment by Jordan-A** [comment]
Here's the implemented fix: https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-conduct/commit/584d447100efb43090e72623a7926083bb6261e7
